### ISSUE TITLE
about converting unet to diffusers format

### ISSUE THREAD

**Issue by WUMINGCHAzero** [KokeCacao/mvdream-hf#2]
Thanks for your great work!
I notice that you commented out the "convert unet" code for converting the unet to diffuers format. Instead, original unet code in MVDream is adopted.  Could you please tell me the reason for doing this？Is there anything wrong when using original diffusers format for unet?

Thanks a lot : )

**Comment by KokeCacao** [comment]
MVDream's unet has 3D self-attention instead of 2D attention, therefore code should be kept. I believe since it is already pytorch code, it isn't very meaningful to change the variable names while keeping the computation identical.

**Comment by WUMINGCHAzero** [comment]
Thanks for responding so quickly!
Thanks for your effort in converting mvdream to diffusers again.
